config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "doctors#index"
  resources :doctors do
    resources :appointments
  end
  resources :patients do
    resources :appointments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
  validates :appointment_date , presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments
    validates :name,:specialties, :phone, presence: true
    validates :phone,  numericality: true, length: {minimum: 10
    }
    paginates_per 2
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :Doctors, through: :appointments
    accepts_nested_attributes_for :appointments
    paginates_per 3

    validates :name,:age,:gender, presence:  { message: "All the field are present"}
    # validates_associated :appointments
    validate :check_age

    private
    def check_age
        if age <18
        errors.add(:age , "must be greater then 20")
        end
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    # def new
    #     @appointment = Appointment.new
    #     @doctor = Doctor.all
    # end
    # def create
    #     # @patient = Patient.find(params[:id])
    #     @appointment = Appointments.create(appointments_params)
    #     if @appointment.save
    #         redirect_to root_path
    #     else
    #         render :new, status: :unprocessabel_entity
    #     end
    # end

    def destroy
    
        @patient = Patient.find(params[:patient_id])
        @appointment = @patient.appointments.find(params[:id])
        @appointment.destroy
        redirect_to @patient
    end

    # private
    # def appointments_params
    #     params.require(:appointment).permit(:appointment_date, :doctor_id, :patient_id)
    # end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def index
        @doctors = Doctor.all.page params[:page]
    end

    def show
        @doctor = Doctor.find(params[:id])
    end

    def new
        @doctor = Doctor.new
    end

    def create
        @doctor = Doctor.create(doctor_params)
        if @doctor.save
            redirect_to @doctor
            # flash[:message] = "Doctor Create successfully!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @doctor = Doctor.find(params[:id])
    end

    def update
        @doctor = Doctor.find(params[:id])
       if  @doctor.update(doctor_params)
        redirect_to @doctor
       else
        render :edit, status: :unprocessabel_entity
       end
        
    end
    def destroy
        @doctor = Doctor.find(params[:id])
        @doctor.destroy
        redirect_to @doctor
    end

    private
    def doctor_params
        params.require(:doctor).permit(:name, :specialties, :phone)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def index
        @patients = Patient.all.page params[:page]
    end
    
    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = Patient.new
        @patient.appointments.build
    end

    def create
        @patient = Patient.create(patients_path)
        if @patient.save
            flash[:message] = "Patient Create successfully!"
            redirect_to @patient
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @patient = Patient.find(params[:id])
    end
    def update
        @patient = Patient.find(params[:id])
        if @patient.update(patients_path)
            redirect_to @patient
        else
            render :edit, status: :unprocessabel_entity
        end
    end

    def destroy
        @patient = Patient.find(params[:id])
        @patient.destroy
        redirect_to @patient
     end

    private
    def patients_path
        params.require(:patient).permit(:name, :age, :gender,appointments_attributes:[:appointment_date, :doctor_id, :patient_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<%= render "doctors/nav" %>
<div class="container" style="width:50%">
<h3 class="text-center">Create New Appointment</h3>
<%= form_with model: @appointments do | form | %>
    <div>
    <%= form.label :appointment_date %>
    <%= form.datetime_field :appointment_date, class:"form-control" %>
    </div><br>
    <div>
    <%= form.label :doctor_id %>
    <%= form.collection_select :doctor_id, Doctor.all, :id, :name%>
    </div>
    <!-------------
    # <div>
    # <%= form.label :patient_id %>
    # <%= form.collection_select :patient_id, Patient.all, :id, :name%>
    # </div>
    ---------->
    <%= form.hidden_field :parent_id  %>
    <div>
    <%= form.submit class:"btn btn-success btn-sm" %>
    <%= link_to "Back", patients_path, class:"btn btn-outline-primary btn-sm" %>
    </div>
<%end%>


</div>   
</body>
</html>

app/views/doctors/_nav.html.erb
<nav class ="navbar n">
    <h5 class="text-white">Dr.Appointments<span class="text-primary"> System<span></h5>
</nav>

app/views/doctors/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<%= render "doctors/nav" %>
<div class="container" style="width:50%; margin-top:10px">
<h3> Edit Doctor Details</h3>
<%= form_with model: @doctor do | form | %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
    </div>
    <div>
        <%= form.label :specialties %>
        <%= form.text_field :specialties, class:"form-control" %>
    </div>
    <div>
        <%= form.label :phone %>
        <%= form.telephone_field :phone, class:"form-control" %>
    </div>
    <div><br>
         <%= form.submit class:"btn btn-success btn-sm"%>
         <%= link_to "Bank", root_path, class:"btn btn-outline-primary btn-sm"%>
    </div>  
    <% end %>
 

</div>
    
</body>
</html>

app/views/doctors/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="bg">
<nav class ="navbar n">
<h5 class="text-white">Dr.Appointments<span class="text-primary"> System<span></h5>
<div>
<%= link_to 'New Doctor', new_doctor_path, class:"btn btn-warning btn-sm" %>
<%= link_to 'New Patient', new_patient_path, class:"btn btn-success btn-sm" %>
<%= link_to 'All patient', patients_path, class:"btn btn-primary btn-sm" %>
</div>
</nav>

<h3 class="text-center"> Doctor listing </h3>
    <div class="container bg-white">
      
            <table class="table">
                <thead>
                    <th>Name </th>
                    <th>Specialties </th>
                    <th></th>
                </thead>
            <tbody>
                <% @doctors.each do |doctor |%>
                <tr>
                    <td><%= doctor.name %></td>
                    <td><%= doctor.specialties %></td>
                    <td><%= link_to 'view' , doctor , class:"btn btn-outline-success btn-sm" %></td>
                </tr>
                <% end %>
            </tbody>
            </table>   
          <%= paginate @doctors %> 
    </div>

</body>
</html>

app/views/doctors/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="bg">
<%= render "doctors/nav" %>
<div class="container bg-white" style="width:50%; height:auto; margin-top:10px">
<h3> Add New Doctor</h3>
<%= form_with model: @doctor do | form | %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
        <% @doctor.errors.full_messages_for(:name).each do | message | %>
           <small class="text-danger"> <%= message %></small>
            <% end %>
    </div>
    <div>
        <%= form.label :specialties %>
        <%= form.text_field :specialties, class:"form-control" %>
        <% @doctor.errors.full_messages_for(:specialties).each do | message | %>
            <small class="text-danger"> <%= message %></small>
             <% end %>
    </div>
    <div>
        <%= form.label :phone %>
        <%= form.telephone_field :phone, class:"form-control" %>
        <% @doctor.errors.full_messages_for(:phone).each do | message | %>
            <small class="text-danger"> <%= message %></small>
             <% end %>
    </div>
    <div><br>
         <%= form.submit class:"btn btn-success btn-sm"%>
         <%= link_to "Bank", root_path, class:"btn btn-outline-primary btn-sm"%>
    </div>  
    <% end %>
 

</div>
   
</body>
</html>

app/views/doctors/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="dn">

<nav class ="navbar n">
    <h5 class="text-white">Dr.Appointments<span class="text-primary"> System<span></h5>
    <div>
    <%= link_to 'Edit', edit_doctor_path(@doctor), class:"btn btn-success btn-sm" %>
    <%= link_to 'Delete', doctor_path(@doctor), data:{
        turbo_method: :delete,
        turbo_confirm:"Are you sure ?"
    } , class:"btn btn-danger btn-sm" %>
    </div>
</nav>
<% flash.each do | message | %>
    <div , class="alert alert-success", role="alert">
    <%= message %>
    </div>
    <% end %>
<h5 class="text-center"> Doctor Details </h5>
    <div class="container bg-white", style="width:50%">
   
        <table class= "table text-center">
            <tr>
                <td><strong>Name :-</strong></td>
                <td><%= @doctor.name %></td>
            </tr>
            <tr>
                <td><strong>Specialties :-</strong></td>
                <td><%= @doctor.specialties%></td>
            </tr>
            <tr>
                <td><strong>Contact No :-</strong></td>
                <td><%= @doctor.phone%></td>
            </tr>
        </table> 
    </div>   
    <% if @doctor.appointments.any? %>
    <h5 class="text-center"> Appointments Details </h5>
<div class="container bg-white" style="width:50%">
           
    <table class= "table text-center">
            <thead>
            <th> Appointments Date </th>
            <th> Patient Name</th>
            <th> Gender </th>
            </thead>
        <tbody>
            <% @doctor.appointments.each do | app | %>
            <tr>
                <td><%= app.appointment_date %></td>
                <td><%= app.patient.name %></td>
                <td><%= app.patient.gender%></td>
            </tr>
            <% end %>
        </tbody>
    </table> 
   <p class="text-center"> <%= link_to "Back" , root_path, class:"btn btn-primary btn-sm" %></p>
</div>
<% else %>
<p class="text-center"> <%= link_to "Back" , root_path, class:"btn btn-primary btn-sm" %></p>

<% end %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<%= render "doctors/nav" %>
<div class="container" style="width:50%; margin-top:10px">
<h3> Edit Patient Details</h3>
<%= form_with model: @patient do | form | %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
    </div>
    <div>
        <%= form.label :age %>
        <%= form.text_field :age, class:"form-control" %>
    </div>
    <div>
        <%= form.label :gender %> &nbsp
        <%= form.radio_button :gender,"male" %>
        <%= form.label :gender, "Male" %>
        <%= form.radio_button :gender,"Female" %>
        <%= form.label :gender, "Female" %>
    </div>
    <div>
         <%= form.submit class:"btn btn-success btn-sm"%>
         <%= link_to "Bank", patient_path, class:"btn btn-outline-primary btn-sm"%>
    </div>  
    <% end %>
</div>   
</body>
</html>

app/views/patients/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="pb">
<nav class ="navbar n">
    <h5 class="text-white">Dr.Appointments<span class="text-primary"> System<span></h5>
    <%= link_to 'New Patient', new_patient_path, class:"btn btn-success btn-sm" %> 
</nav>
<h3 class="text-center"> Patient listing </h3>
    <div class="container bg-white">       
    <table class="table">
            <thead>
                <th>Name </th>
                <th>Age</th>
                <th>Gender</th>
                <th></th>
            </thead>
            <tbody>
                <% @patients.reverse.each do |patient|%>
                    <tr>
                        <td><%= patient.name %></td>
                        <td><%= patient.age %></td>
                        <td><%= patient.gender %></td>
                        <td><%= link_to 'view' , patient , class:"btn btn-outline-success btn-sm" %></td>
                    </tr>
                    <% end %>
            </tbody>
    </table>   
    <%= link_to "Back", root_path, class:"btn btn-primary btn-sm" %> 
    <%= paginate @patients %>
    </div>  
</body>
</html>

app/views/patients/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="bg">
<%= render "doctors/nav" %>
<div class="container bg-white" style="width:50% ;height: auto; margin-top:10px">
<h3 class="text-center"> Add New Patient</h3>
<%= form_with model: @patient do | form | %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
        <% @patient.errors.full_messages_for(:name).each do | message | %>
            <small class="text-danger"> <%= message %></small>
             <% end %>
    </div>
    <div>
        <%= form.label :age %>
        <%= form.text_field :age, class:"form-control" %>
        <% @patient.errors.full_messages_for(:age).each do | message | %>
            <small class="text-danger"> <%= message %></small>
             <% end %>
    </div>
    <div>
        <%= form.label :gender %> &nbsp
        <%= form.radio_button :gender,"male" %>
        <%= form.label :gender, "Male" %>
        <%= form.radio_button :gender,"Female" %>
        <%= form.label :gender, "Female" %>
        <% @patient.errors.full_messages_for(:gender).each do | message | %>
            <small class="text-danger"> <%= message %></small>
             <% end %>
    </div>
    <h4> Appointment details :- </h4>
    <%= form.fields_for :appointments do | app_form | %>
        <div>
        <%= app_form.label :appointment_date %>
        <%= app_form.datetime_field :appointment_date , class:"form-control"%>
        </div><br>
        <div>
        <%= app_form.label :doctor_id %>
        <%= app_form.collection_select :doctor_id, Doctor.all, :id, :name%>
        </div>
        <% end %>
    <div>
         <%= form.submit class:"btn btn-success btn-sm"%>
         <%= link_to "Bank", root_path, class:"btn btn-outline-primary btn-sm"%>
    </div>  
    <% end %>
 

</div>
   
</body>
</html>

app/views/patients/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="dn">
<nav class ="navbar n">
<h5 class="text-white">Dr.Appointments<span class="text-primary"> System<span></h5>
<div>
<%= link_to 'Edit',edit_patient_path(@patient) , class:"btn btn-warning btn-sm" %>
<%= link_to "Delete", patient_path(@patient), data:{
    turbo_method: :delete,
    turbo_confirm:"Are you sure?"
}, class:"btn btn-danger btn-sm" %>
</div>
</nav>
<% flash.each do | message | %>
    <div class="alert alert-success", role="alert">
    <%= message %>
    </div>
<% end %>
<h5 class="text-center"> Patient Details </h5>

<div class="container bg-white", style="width:50%">

    <table class= "table text-center">
        <tr>
            <td><strong>Name :-</strong></td>
            <td><%= @patient.name %></td>
        </tr>
        <tr>
            <td><strong>Age:-</strong></td>
            <td><%= @patient.age%></td>
        </tr>
        <tr>
            <td><strong>Gender:-</strong></td>
            <td><%= @patient.gender%></td>
        </tr>
    </table> 

</div>       
<% if @patient.appointments.present? %>
<h5 class="text-center"> patient Appointments Details </h5>
<div class="container bg-white" style="width:50%">
           
    <table class= "table text-center">
            <thead>
            <th> Appointments Date </th>
            <th> Doctor Name</th>
            <th> Specialties</th>
            <th> </th>
            </thead>
        <tbody>
            <% @patient.appointments.each do | app | %>
            <tr>
                <td><%= app.appointment_date %></td>
                <td><%= app.doctor.name %></td>
                <td><%= app.doctor.specialties %></td>
                <td><%= link_to "Delete",  patient_appointment_path(@patient, app.id) , class:"btn btn-danger btn-sm", data:{
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"}%></td>
            </tr>
            <% end %>
        </tbody>
    </table> 
   <p class="text-center"> <%= link_to "Back" , patients_path, class:"btn btn-primary btn-sm" %></p>
</div>   
<% else %>
<p class="text-center"> <%= link_to "Back" , patients_path, class:"btn btn-primary btn-sm" %></p>
<% end %>
</body>
</html>